project:
  type: website
  output-dir: docs

# Meta
description-meta: "Assistant Professor of Political Science. Research on comparative politics, statistics, data science, and historical political economy."
author-meta: "Bogdan Popescu"

website:
  title: "Bogdan Popescu"
  site-url: "https://bgpopescu.net"
  description: "Comparative politics • statistics • data science • historical political economy"
  page-navigation: true

  navbar:
    background: light
    left:
      - href: research.qmd
        text: Research
      - href: books.qmd
        text: Books
      - href: teaching.qmd
        text: Teaching
      - href: contact.qmd
        text: Contact
    right:
      - text: CV
        href: https://www.dropbox.com/scl/fi/optcr0vsvyxd4nv6yfl12/bogdan-popescu-cv.pdf?rlkey=l36m9959xuey04nsrlzrzz05r&e=2&dl=0
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/bogdanpopescu/
        target: _blank
      - icon: github
        href: https://github.com/bgpopescu
        target: _blank
      - text: "![](/images/bluesky_logo.svg){height=1em}"
        href: https://bsky.app/profile/bgpopescu.bsky.social
        target: _blank
      - text: "![](/images/x_logo.png){height=1em}"
        href: https://x.com/BogdanGPopescu1
        target: _blank
    
  search:
    location: navbar
    type: textbox

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
